# Generated by Django 2.2.12 on 2020-06-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='assigned_patients',
            field=models.ManyToManyField(blank=True, to='patients.PatientProfile'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='list_of_classes',
            field=models.ManyToManyField(blank=True, to='experts.ExpertClass'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='message',
            field=models.ManyToManyField(blank=True, to='patients.Messages'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'Expert'}, on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertclass',
            name='class_modules',
            field=models.ManyToManyField(blank=True, to='experts.ClassModules'),
        ),
        migrations.AddField(
            model_name='expertclass',
            name='members',
            field=models.ManyToManyField(blank=True, to='patients.PatientProfile'),
        ),
    ]
