# Generated by Django 2.2.12 on 2020-05-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20200527_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='expertclass',
            name='class_modules',
            field=models.ManyToManyField(blank=True, to='experts.ClassModules'),
        ),
    ]
