# Generated by Django 2.2.12 on 2020-05-27 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('receiver_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.ExpertClass')),
            ],
        ),
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='General', max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned_experts', models.ManyToManyField(blank=True, to='experts.ExpertProfile')),
                ('group_member', models.ManyToManyField(blank=True, to='patients.PatientGroup')),
                ('list_of_classes', models.ManyToManyField(blank=True, to='experts.ExpertClass')),
                ('message', models.ManyToManyField(blank=True, to='patients.Messages')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver_expert',
            field=models.ForeignKey(on_delete=models.SET(patients.models.get_custom_user), related_name='receiver_expert', to='patients.PatientProfile'),
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_group', to='patients.PatientGroup'),
        ),
    ]
