# Generated by Django 2.2.12 on 2020-05-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
