# Generated by Django 2.2.12 on 2020-05-25 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='General', max_length=240, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('receiver_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.ExpertClass')),
                ('receiver_expert', models.ForeignKey(on_delete=models.SET(patients.models.get_custom_user), related_name='receiver_expert', to='patients.PatientProfile')),
                ('receiver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_group', to='patients.PatientGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Expert'}, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.ExpertClass'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_experts',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(patients.models.get_custom_user), to='patients.ExpertProfile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='group_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.PatientGroup'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Messages'),
        ),
    ]
