# Generated by Django 2.2.12 on 2020-05-25 21:19

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200525_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='assigned_experts',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(patients.models.get_custom_user), to='authapp.ExpertProfile'),
        ),
        migrations.DeleteModel(
            name='ExpertProfile',
        ),
    ]
