# Generated by Django 2.2.12 on 2020-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200527_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='username',
            field=models.CharField(blank=True, default='user', max_length=50),
        ),
    ]
