# Generated by Django 2.2.12 on 2020-05-29 00:30

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver_expert',
            field=models.ForeignKey(blank=True, on_delete=models.SET(patients.models.get_custom_user), related_name='receiver_expert', to='patients.PatientProfile'),
        ),
    ]
