# Generated by Django 2.2.12 on 2020-05-29 00:31

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200529_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(patients.models.get_custom_user), related_name='receiver_expert', to='patients.PatientProfile'),
        ),
    ]
