# Generated by Django 2.2.12 on 2020-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200525_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='message',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='patients.Messages'),
        ),
    ]
