# Generated by Django 2.2.12 on 2020-05-29 01:18

from django.conf import settings
from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_auto_20200529_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(patients.models.get_custom_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
