# Generated by Django 2.2.12 on 2020-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('patients', '0005_auto_20200526_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='list_of_classes',
            field=models.ManyToManyField(blank=True, to='patients.ExpertClass'),
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='assigned_experts',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_experts',
            field=models.ManyToManyField(blank=True, to='authapp.ExpertProfile'),
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='group_member',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='group_member',
            field=models.ManyToManyField(blank=True, to='patients.PatientGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='message',
            field=models.ManyToManyField(blank=True, to='patients.Messages'),
        ),
    ]
