# Generated by Django 2.2.12 on 2020-05-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Expert', 'Expert'), ('Patient', 'Patient')], default='Patient', max_length=10),
        ),
    ]
